Implemented Hot Module Reloading for Vuex
Fixes:
TypeError: Cannot read property 'extend' of undefined
Something went wrong during Vue component hot-reload. Full reload required.